address: 0.0.0.0:7777
backend: localhost:{{ .HTTPPort }}
tenant_header_key: {{ .TenantHeader }}
{{- if and .Gates.HTTPEncryption .Gateway }}
tls_enabled: true
tls_cert_path: {{ .TLS.Paths.Certificate }}
tls_key_path: {{ .TLS.Paths.Key }}
tls_ca_path: {{ .TLS.Paths.CA }}
tls_insecure_skip_verify: false
tls_server_name: {{ .TLS.ServerNames.QueryFrontend }}
{{- end }}
services_query_duration: {{ .ServicesQueryDuration }}
find_traces_concurrent_requests: {{ .FindTracesConcurrentRequests }}
