overrides:
{{- range $name, $value := .TenantOverrides }}
  "{{ $name }}":
    ingestion:
{{- if $value.IngestionBurstSizeBytes }}
      burst_size_bytes: {{ $value.IngestionBurstSizeBytes }}
{{- end }}
{{- if $value.IngestionRateLimitBytes }}
      rate_limit_bytes: {{ $value.IngestionRateLimitBytes }}
{{- end }}
{{- if $value.MaxTracesPerUser }}
      max_traces_per_user: {{ $value.MaxTracesPerUser }}
{{- end }}
{{- if $value.MaxBytesPerTrace }}
      max_bytes_per_trace: {{ $value.MaxBytesPerTrace }}
{{- end }}
    read:
{{- if $value.MaxBytesPerTagValues }}
      max_bytes_per_tag_values_query: {{ $value.MaxBytesPerTagValues }}
{{- end }}
{{- if ne $value.MaxSearchDuration "0s" }}
      max_search_duration: {{ $value.MaxSearchDuration }}
{{- end }}
{{- if $value.BlockRetention  }}
    compaction:
      block_retention: {{ $value.BlockRetention }}
{{- end }}
{{- end }}
