namespace: tempo-operator-system

namePrefix: tempo-operator-

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
