# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: configuration
spec:
  parallel: 4
  timeouts:
    apply: 30s
    assert: 5m
    cleanup: 5m
    delete: 5m
    error: 5m
    exec: 5m
