# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: configuration
spec:
  parallel: 1
  timeouts:
    assert: 5m0s
    cleanup: 5m0s
    delete: 5m0s
    error: 5m0s
    exec: 5m0s
  catch:
    - get:
        apiVersion: tempo.grafana.com/v1alpha1
        kind: TempoStack
        format: yaml
    - get:
        apiVersion: tempo.grafana.com/v1alpha1
        kind: TempoMonolithic
        format: yaml
    - podLogs:
        selector: app.kubernetes.io/managed-by=tempo-operator
        tail: 100
    - podLogs:
        selector: job-name
        tail: 100
    - podLogs:
        namespace: tempo-operator-system
        selector: app.kubernetes.io/part-of=tempo-operator
        tail: 100
    - podLogs:
        namespace: openshift-tempo-operator
        selector: app.kubernetes.io/part-of=tempo-operator
        tail: 100
    - events: {}
