coverage:
  status:
    project:
      default:
        target: auto
        # this allows a 0.1% drop from the previous base commit coverage
        threshold: 0.1%
ignore:
  - "apis/config/v1alpha1/zz_generated.deepcopy.go"
  - "apis/config/v1alpha1/groupversion_info.go"
  - "apis/tempo/v1alpha1/zz_generated.deepcopy.go"
  - "apis/tempo/v1alpha1/groupversion_info.go"
