version: "2"
linters:
  enable:
    - exhaustive
    - godot
    - gosec
    - misspell
    - revive
    - unparam
  settings:
    govet:
      disable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: _test\.go
      - path: cmd/root.go
        text: 'SA1019: options.AndFrom is deprecated'
      - path: cmd/root.go
        text: 'SA1019: ctrl.ConfigFile is deprecated'
      - path: apis/config/v1alpha1/projectconfig_types.go
        text: 'SA1019: "sigs.k8s.io/controller-runtime/pkg/config/v1alpha1" is deprecated'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/grafana/tempo-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
