resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/grafana/tempo-operator/tempo-operator
  newTag: v0.19.0@sha256:174cdd56891ebfcaa9e4d92a0f839db034fd9f1cf50cc161f94c56e848384f02
