apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: tracing
spec:
  observability:
    metrics:
      enableMetrics: true
  config:
    extensions:
      bearertokenauth:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831

    connectors:
      spanmetrics:
        dimensions:
        - name: k8s.namespace.name
        - name: k8s.deployment.name
        - name: k8s.statefulset.name
        - name: k8s.daemonset.name
        - name: k8s.container.name
        - name: k8s.cronjob.name
        - name: k8s.node.name
        - name: k8s.cluster.name

    processors:
      k8sattributes: {}

    exporters:
      otlp/project1:
        endpoint: tempo-tempo1-gateway.tracing.svc.cluster.local:8090
        tls:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: project1
      prometheus:
        endpoint: 0.0.0.0:8889

    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [k8sattributes]
          exporters: [otlp/project1, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          processors: []
          exporters: [prometheus]
