apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.23.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: tempo-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Simpilifes the deployment of tempo db.
  displayName: tempo-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tempo
  - tracing
  - database
  links:
  - name: Tempo Operator
    url: https://tempo-operator.domain
  maintainers:
  - email: ruben.vp8510@gmail.com
    name: Ruben Vargas
  - email: p.loffay@gmail.com
    name: Pavol Loffay
  - email: kearls@redhat.com
    name: Kevin Earls
  - email: bongartz@klimlive.de
    name: Benedikt Bongartz
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
