FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40

RUN apk update &&       \
    apk add --no-cache curl jq bash &&  \
    rm -rf /var/cache/apk/*

CMD [ "bash" ]
