FROM alpine:3.18@sha256:de0eb0b3f2a47ba1eb89389859a9bd88b28e82f5826b6969ad604979713c2d4f

RUN apk update &&       \
    apk add --no-cache curl jq bash &&  \
    rm -rf /var/cache/apk/*

CMD [ "bash" ]
