---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tempo-grafana-com-v1alpha1-tempostack
  failurePolicy: Fail
  name: mtempostack.tempo.grafana.com
  rules:
  - apiGroups:
    - tempo.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tempostacks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tempo-grafana-com-v1alpha1-tempomonolithic
  failurePolicy: Fail
  name: vtempomonolithic.kb.io
  rules:
  - apiGroups:
    - tempo.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tempomonolithics
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-tempo-grafana-com-v1alpha1-tempostack
  failurePolicy: Fail
  name: vtempostack.tempo.grafana.com
  rules:
  - apiGroups:
    - tempo.grafana.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tempostacks
  sideEffects: None
