# permissions for end users to edit tempooperatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempooperatorconfig-editor-role
rules:
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempooperatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempooperatorconfigs/status
  verbs:
  - get
