# permissions for end users to view tempostacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-viewer-role
rules:
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempostacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempostacks/status
  verbs:
  - get
