apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: sample
spec:
  storageSize: 1Gi
  storage:
    secret:
      name: object-storage
      type: s3
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
