apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tempo
  namespace: operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: tempo-operator
  source: tempo-catalog
  sourceNamespace: operators
