resources:
- ../../default
- ../../prometheus
# Grant cluster-monitoring access to openshift-operators-redhat metrics
- prometheus_role.yaml
- prometheus_role_binding.yaml

# Adds namespace to all resources.
namespace: openshift-operators-redhat

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: tempo-operator-

labels:
- pairs:
    app.kubernetes.io/name: tempo-operator
    app.kubernetes.io/part-of: tempo-operator
    app.kubernetes.io/managed-by: operator-lifecycle-manager
  includeSelectors: true

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

patchesStrategicMerge:
- metrics_service_tls_patch.yaml
- manager_auth_proxy_tls_patch.yaml
- service_monitor_patch.yaml
