baseURL = 'https://tempo-operator.dev/'
languageCode = 'en-us'
title = 'Tempo Operator'
theme = 'doks'

[permalinks]
  docs = "/:sections/:filename.md"

[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 1
